spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
        auto.register.schemas: true

kafka:
  topic:
    name: weather_input

weather:
  api:
    url: "https://api.open-meteo.com/v1/forecast?latitude=51.42&longitude=5.46&current_weather=true"
  fetch:
    run-on-startup: true
    cron: "0 */15 * * * *"